import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Picker } from "@react-native-picker/picker";
import { router } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View, type ListRenderItem } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { filterUpcomingArrivals, formatShipTime, getFilterValues, setActiveShipRecords, SHIP_STATUS_META, type ShipRecord } from "@/lib/ships";
import { trpc } from "@/lib/trpc";

function ArrivalCard({ ship }: { ship: ShipRecord }) {
  const meta = SHIP_STATUS_META[ship.status];
  return <Pressable accessibilityHint="開啟船舶完整資訊" accessibilityLabel={`${ship.name} 的入港預報`} onPress={() => router.push(`/ship/${ship.id}` as never)} style={({ pressed }) => [styles.card, pressed && styles.cardPressed]}><View style={styles.cardHeader}><View style={styles.titleBlock}><Text numberOfLines={1} style={styles.shipName}>{ship.name}</Text><Text style={styles.voyage}>航次 {ship.voyage} · IMO {ship.imo}</Text></View><View style={[styles.statusChip, { backgroundColor: meta.softColor, borderColor: meta.borderColor }]}><MaterialIcons color={meta.color} name={meta.icon} size={15} /><Text style={[styles.statusText, { color: meta.color }]}>{meta.label}</Text></View></View><View style={styles.divider} /><View style={styles.etaPanel}><View style={styles.etaIcon}><MaterialIcons color="#137A9B" name="south" size={19} /></View><View><Text style={styles.etaLabel}>預計入港</Text><Text style={styles.etaValue}>{formatShipTime(ship.eta)}</Text></View></View><View style={styles.infoRow}><View style={styles.infoCell}><Text style={styles.infoLabel}>來源港</Text><Text numberOfLines={1} style={styles.infoValue}>{ship.originPort}</Text></View><View style={styles.infoCell}><Text style={styles.infoLabel}>預定泊位</Text><Text numberOfLines={1} style={styles.infoValue}>{ship.berth}</Text></View><MaterialIcons color="#0B4F71" name="chevron-right" size={22} /></View></Pressable>;
}

function FilterPicker({ label, value, items, onChange }: { label: string; value: string; items: string[]; onChange: (value: string) => void }) {
  return <View style={styles.pickerBlock}><Text style={styles.pickerLabel}>{label}</Text><View style={styles.pickerShell}><Picker selectedValue={value} onValueChange={onChange} style={styles.picker}><Picker.Item label={`全部${label}`} value="all" />{items.map((item) => <Picker.Item key={item} label={item} value={item} />)}</Picker></View></View>;
}

export default function ArrivalsScreen() {
  const [berth, setBerth] = useState("all");
  const [vesselType, setVesselType] = useState("all");
  const [nameFilter, setNameFilter] = useState("");
  const [originPortFilter, setOriginPortFilter] = useState("");
  const { data: snapshot, isFetching, isLoading, refetch } = trpc.ships.snapshot.useQuery(undefined, { staleTime: 60_000, refetchInterval: 10 * 60 * 1000, refetchIntervalInBackground: false, refetchOnWindowFocus: false });
  const refreshShips = trpc.ships.refresh.useMutation();
  const records = useMemo(() => snapshot?.ships ?? [], [snapshot?.ships]);
  const berthOptions = useMemo(() => getFilterValues(records, "berth"), [records]);
  const vesselTypeOptions = useMemo(() => getFilterValues(records, "vesselType"), [records]);
  const upcomingArrivals = useMemo(() => filterUpcomingArrivals(records, berth, vesselType, { name: nameFilter, originPort: originPortFilter }), [berth, nameFilter, originPortFilter, records, vesselType]);

  useEffect(() => { setActiveShipRecords(records); }, [records]);
  const renderArrival: ListRenderItem<ShipRecord> = ({ item }) => <ArrivalCard ship={item} />;
  const handleRefresh = useCallback(async () => {
    await refreshShips.mutateAsync();
    await refetch();
  }, [refreshShips, refetch]);

  return <ScreenContainer containerClassName="bg-background" edges={["top", "left", "right"]}><FlatList contentContainerStyle={styles.listContent} data={upcomingArrivals} keyExtractor={(item) => item.id} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl colors={["#0B4F71"]} onRefresh={handleRefresh} refreshing={isFetching && !isLoading} tintColor="#0B4F71" title="正在同步進港預報…" titleColor="#506773" />} ListEmptyComponent={<View style={styles.emptyState}><View style={styles.emptyIcon}><MaterialIcons color="#0B4F71" name={snapshot?.source === "unavailable" ? "cloud-off" : "schedule"} size={28} /></View><Text style={styles.emptyTitle}>{snapshot?.source === "unavailable" ? "暫時無法取得官方預報" : "暫無符合的進港預報"}</Text><Text style={styles.emptyBody}>{snapshot?.notice ?? "請調整篩選條件，或稍後再次更新。"}</Text></View>} ListHeaderComponent={<View><Text style={styles.eyebrow}>ARRIVAL FORECAST</Text><Text style={styles.heading}>24H 入港預報</Text><Text style={styles.subheading}>依高雄港官方進港預報資料呈現未來 24 小時船舶</Text><View style={styles.summaryPanel}><MaterialIcons color="#176B85" name="directions-boat" size={23} /><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>{upcomingArrivals.length} 艘準備入港</Text><Text style={styles.summaryText}>已依泊位、船型、來源港與船名條件篩選</Text></View></View><View style={styles.filters}><FilterPicker label="泊位" value={berth} items={berthOptions} onChange={setBerth} /><FilterPicker label="船型" value={vesselType} items={vesselTypeOptions} onChange={setVesselType} /></View><View style={styles.advancedPanel}><Text style={styles.fieldLabel}>來源港</Text><TextInput accessibilityLabel="依來源港篩選入港預報" clearButtonMode="while-editing" onChangeText={setOriginPortFilter} placeholder="例如：新加坡、台中港" placeholderTextColor="#7C8D98" returnKeyType="done" style={styles.advancedInput} value={originPortFilter} /><Text style={styles.fieldLabel}>船名</Text><TextInput accessibilityLabel="依船名篩選入港預報" autoCapitalize="characters" clearButtonMode="while-editing" onChangeText={setNameFilter} placeholder="例如：EVER、MAERSK" placeholderTextColor="#7C8D98" returnKeyType="done" style={styles.advancedInput} value={nameFilter} />{nameFilter || originPortFilter ? <Pressable onPress={() => { setNameFilter(""); setOriginPortFilter(""); }} style={({ pressed }) => [styles.clearAdvanced, pressed && styles.buttonPressed]}><Text style={styles.clearAdvancedText}>清除進階條件</Text></Pressable> : null}</View>{upcomingArrivals.length > 0 ? <Text style={styles.listLabel}>進港船舶</Text> : null}</View>} renderItem={renderArrival} showsVerticalScrollIndicator={false} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  listContent: { flexGrow: 1, paddingBottom: 28, paddingHorizontal: 20, paddingTop: 18 }, eyebrow: { color: "#137A9B", fontSize: 11, fontWeight: "800", letterSpacing: 1.1, lineHeight: 16 }, heading: { color: "#173042", fontSize: 31, fontWeight: "800", letterSpacing: -0.5, lineHeight: 40, marginTop: 2 }, subheading: { color: "#657984", fontSize: 14, lineHeight: 21 }, summaryPanel: { alignItems: "center", backgroundColor: "#EAF5F8", borderColor: "#C9E4EC", borderRadius: 16, borderWidth: 1, flexDirection: "row", marginTop: 21, padding: 13 }, summaryCopy: { marginLeft: 10 }, summaryTitle: { color: "#173042", fontSize: 14, fontWeight: "800", lineHeight: 20 }, summaryText: { color: "#537180", fontSize: 12, lineHeight: 18, marginTop: 1 },
  filters: { gap: 12, marginTop: 16 }, pickerBlock: { width: "100%" }, pickerLabel: { color: "#506773", fontSize: 13, fontWeight: "800", lineHeight: 18, marginBottom: 6 }, pickerShell: { backgroundColor: "#FFFFFF", borderColor: "#D6E1E7", borderRadius: 12, borderWidth: 1, height: 50, justifyContent: "center", overflow: "hidden", width: "100%" }, picker: { color: "#173042", fontSize: 15, height: 50, width: "100%" }, advancedPanel: { backgroundColor: "#F4FAFC", borderColor: "#D4E8EE", borderRadius: 14, borderWidth: 1, marginTop: 14, padding: 12 }, fieldLabel: { color: "#506773", fontSize: 12, fontWeight: "800", marginBottom: 6 }, advancedInput: { backgroundColor: "#FFFFFF", borderColor: "#D6E1E7", borderRadius: 10, borderWidth: 1, color: "#173042", fontSize: 14, height: 44, marginBottom: 11, paddingHorizontal: 11, paddingVertical: 0 }, clearAdvanced: { alignSelf: "flex-start", minHeight: 30 }, clearAdvancedText: { color: "#176B85", fontSize: 12, fontWeight: "800" }, listLabel: { color: "#173042", fontSize: 17, fontWeight: "800", marginBottom: 10, marginTop: 25 },
  card: { backgroundColor: "#FFFFFF", borderColor: "#DCE6EB", borderRadius: 16, borderWidth: 1, marginBottom: 11, padding: 15 }, cardPressed: { opacity: 0.78, transform: [{ scale: 0.985 }] }, cardHeader: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, titleBlock: { flex: 1, marginRight: 10 }, shipName: { color: "#173042", fontSize: 16, fontWeight: "800", letterSpacing: 0.1, lineHeight: 22 }, voyage: { color: "#657984", fontSize: 12, fontWeight: "600", lineHeight: 18, marginTop: 2 }, statusChip: { alignItems: "center", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: 4, minHeight: 28, paddingHorizontal: 8 }, statusText: { fontSize: 12, fontWeight: "800" }, divider: { backgroundColor: "#E8EEF1", height: 1, marginVertical: 12 }, etaPanel: { alignItems: "center", backgroundColor: "#F0F8FA", borderRadius: 10, flexDirection: "row", marginBottom: 11, padding: 9 }, etaIcon: { alignItems: "center", backgroundColor: "#DDF0F5", borderRadius: 14, height: 28, justifyContent: "center", width: 28 }, etaLabel: { color: "#536F7B", fontSize: 11, lineHeight: 15, marginLeft: 8 }, etaValue: { color: "#1F4F61", fontSize: 13, fontWeight: "800", lineHeight: 19, marginLeft: 8 }, infoRow: { alignItems: "center", flexDirection: "row" }, infoCell: { flex: 1, paddingRight: 8 }, infoLabel: { color: "#71838D", fontSize: 11, lineHeight: 16 }, infoValue: { color: "#284252", fontSize: 12, fontWeight: "700", lineHeight: 18, marginTop: 1 },
  emptyState: { alignItems: "center", flex: 1, justifyContent: "center", paddingHorizontal: 25, paddingTop: 55 }, emptyIcon: { alignItems: "center", backgroundColor: "#E4F3F8", borderRadius: 25, height: 50, justifyContent: "center", width: 50 }, emptyTitle: { color: "#173042", fontSize: 18, fontWeight: "800", marginTop: 14 }, emptyBody: { color: "#657984", fontSize: 14, lineHeight: 21, marginTop: 5, textAlign: "center" }, buttonPressed: { opacity: 0.74, transform: [{ scale: 0.98 }] },
});
